on:
  push:
    branches:
      - master





jops: 
  build: 
    runs_on: ubuntu_latest

    steps:
      - name:'before'
        run: ls

      - uses: actions/checkout@v3

      - name: 'after'
        run: ls


